### ISSUE TITLE
Add Accessible Command Arguments to Slash Activity

### ISSUE THREAD

**Issue by ystan-** [finos/symphony-bdk-java#511]
### Description of Problem:
Slash commands that perform more complex tasks are usually accompanied with additional arguments behind the command itself. An example would be `/buy $GOOG 2mm` to represent a buy order for the ticker GOOG with a quantity of 2mm.

Using the BDK's `@Slash` annotation, it is currently not straightforward to extract the list of arguments.
An example of what a developer would currently do is:
- Autowire the SessionService
- Create an `@Slash` annotated method with a `.*` suffix in the command pattern
- Use SessionService to get the bot's own display name
- Extract the message text, sub-string it by the display name + 2 (for @ and space)
- Sub-string it further by the index of the first space
  - Assuming the command is a single-word here, since we have no access to the annotation value from the CommandContext
- Split the result by spaces

```java
@Autowired
private final SessionService sessionService;

@Slash("/buy .*")
public void onBuy(CommandContext context) {
  String displayName = sessionService.getSession().getDisplayName();
  String messageText = context.getTextContent().trim().substring(displayName.length() + 2);
  String[] arguments = messageText.substring(messageText.indexOf(" ") + 1).split(" ");
  String ticker = arguments[0];
  String quantity = arguments[1];
  // ... also remember to handle case without @mention prefix
}
```

### Potential Solutions:
In order of preference:
1. Support a Spring MVC-like convention when declaring `@Slash`
```java
@Slash("/buy {ticker} {quantity}")
public void onBuy(
  CommandContext context,
  @CommandArgument String ticker,
  @CommandArgument String quantity
) { ... }
```
2. Add a convenience method to the context object itself: e.g. `CommandContext::getArguments()`
3. Add a convenience class/service to extract the arguments like what was done for `PresentationMLPaser::getTextContent(String)`

**Comment by symphony-youri** [comment]
To help implement it, [AntPathMatcher](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html) might be useful

**Comment by symphony-elias** [comment]
Discussion on a PoC here: #595

**Comment by symphony-elias** [comment]
What we are thinking of actually implementing:

**Phase 1**
* Command pattern format:
`"/command {myarg} {@mention} {$cashtag} {#hashtag}"`
All arguments are Strings by default.
* Whitespace is a strong separator, two arguments must be separated by a space.
Patterns like `"/command {arg1}{arg2}"` will be rejected
One argument is a sequence of non-whitespace characters.
* No ability to specify regex pattern for arguments (Phase 2)
* No support of catch all arguments, varargs or list of arguments, no support of optional arguments (Phase 2)
* BDK Core API: keep it backward compatible. CommandContext will contain a `Map<String, Object>` containing arguments with key = argument name, value = argument value. Actual type will depend on the type in the command pattern:
** String by default
** Mention in case of {@mention}
** Cashtag in case of {$cashtag}
** HashTag in case of {#hashtag}

* SpringBoot API: keep it backward compatible
```
@Component
public class MyActivity {
  @Slash("/echo {one} {two} {@three")
  public void echo(CommandContext context, Integer one, String two, Mention three) {
    // implementation
  }
}
```
If the `{one}` argument cannot be parsed into an Integer, then we consider it is not matching and we don’t call the method. Same for other numerical types.

* Implement a more reliable mention parser from a V4MessageSent event object. Check if we could reuse AntPathMatcher (most probably not the case), write our own pattern matching algorithm otherwise.

**Phase 2**
These are ideas of what we could implement later:

* Regex matching for arguments like: `"/command {arg1:[0-9]+}"`
* Catch all argument only at the end of the pattern: "/command {arg1} {arg2:.+}"
* List arguments (aka varargs)
* Optional arguments

**Comment by robmoffat** [comment]
If it helps, @symphony-elias, we've already implemented this in our toolkit.  @sureshrupnar is looking at porting what we have to use the BDK over the next month.  

We can show you what we've been up to if you want.

**Comment by symphony-elias** [comment]
This has been delivered in https://github.com/finos/symphony-bdk-java/releases/tag/2.5.0.RC1
