### ISSUE TITLE
ConnectionService retries on error when it should not

### ISSUE THREAD

**Issue by giso-cmo** [finos/symphony-bdk-java#578]
### Steps to Reproduce:
Using the ConnectionService, accept a connection request using connectionService.acceptConnection(userId), for a user with a connection that has StatusEnum ACCEPTED.

### Expected Result:
To throw the following error once:

`An unknown error occurred while trying to connect to https://[...]:443/pod. Please check below for more information: {"code":500,"message":"request to userConnections/[...] failed with status 422, message:Status change requested is not consistent with current status."} `

### Actual Result:
Instead, the RetryWithRecovery kicks in and the connection service keeps trying to accept, each time throwing the same error

### Environment:
symphony-bdk 2.2.1

**Comment by symphony-thibault** [comment]
Thanks @giso-cmo for this report 👍 

Your issue seems to be related to https://github.com/finos/symphony-bdk-java/pull/509, where we decided to retry on `500` errors. 

However, from the log trace you shared above, it looks like the Symphony Backend is returning `500` because of a `422` received from an internal component. Which is the actual issue. 

I'll sync internally to make sure this issue resolved in the next release, and keep you in touch through this ticket. 

Thibault.

**Comment by ystan-** [comment]
Update: this scenario now correctly returns 400 instead of 500 so the tooling also now responds correctly without requiring any changes
