### ISSUE TITLE
Enums are not flexible on new fields

### ISSUE THREAD

**Issue by symphony-mariacristina** [finos/symphony-bdk-java#592]
### Steps to Reproduce:
- Make sure pod contains SDL users
- Call Users lookup endpoint (GET /pod/v3/users/), using BDK with version  <= 2.2.1

### Expected Result:
Even if the generated model do not contain the value "SDL" in the enum as a valid account type, the BDK should still be able to parse the results.

### Actual Result:
BDK fails with the following exception:
```
java.lang.IllegalArgumentException: Unexpected value 'SDL'
at com.symphony.bdk.gen.api.model.UserV2$AccountTypeEnum.fromValue(UserV2.java:117)
```

**Comment by symphony-thibault** [comment]
@symphony-mariacristina @symphony-youri the only solution I see on library side is to modify the [modelInnerEnum.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/modelInnerEnum.mustache) in order to[ enforce returning `null` instead of throwing `IllegalArgumentException` ](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/modelInnerEnum.mustache#L58) if the generated code is not up-to-date.

This is clearly not the best solution, but at least it will give avoid breaking any API call in case we add new value in the future.

**Comment by symphony-youri** [comment]
Given we cannot change the existing APIs/models
And that some of them are already using enums
I don't see a better solution, at least this way we might not break some of users in the future (right now all the users of the BDK would have to update anyway). They would get null enums in case new values are added but this might be ok if they don't use it.

Maybe we could add a default value to all existing enums (UNKNOWN) that could be returned instead of null but in this case I'm not sure we are not breaking compatibility anyway (https://wiki.eclipse.org/Evolving_Java-based_APIs_2 seems to say it would be ok).

Could we maybe evaluate the affected enums in the recent releases? (or is it only AccountType SDL?)

There is also https://github.com/OAI/OpenAPI-Specification/issues/1552 on this topic.
