### ISSUE TITLE
Limitation for multipart/form-data form

### ISSUE THREAD

**Issue by imadamahmid1** [finos/symphony-bdk-java#631]
## Feature Request
The current httpClient of bdk doesn't support multiple values for a given form key. 
With the current httpClient of bdk, this works: 
```java
httpClient.formParam("file", new File("path/to/myFile/");
```

But when we keep adding other files like the snippet bellow doesn't work because we keep overriding the map containing the parameters:
```java
httpClient.formParam("file", new File("path/to/myFirstFile/");
httpClient.formParam("file", new File("path/to/mySecondFile/");
```

### Description of Problem:
 I checked the code and it seems like the form params are stored in a map, and the value of "file" will be overridden each time which will prevent us from having a field with many files. The implementation ideally would support adding of multiple files under the same key and use boundary to separate the files under the field **_file_**.

Ideally we want to to be able to add several files in one field of form data in an iterative way, like this:
```java
httpClient.formParam("file", new File("path/to/myFirstFile/");
httpClient.formParam("file", new File("path/to/mySecondFile/");
httpClient.formParam("file", new File("path/to/myThirdFile/");
```

### Potential Solutions:
N/A

**Comment by symphony-elias** [comment]
We could think of several solutions:

- user passes a `List<File>` as form param and we update the `ApiClientWebClient` and `ApiClientJersey2` implementations to handle a list of files (list of strings are already handled for urlencoded forms): https://github.com/finos/symphony-bdk-java/blob/b77d36a2ca6fa6000f8fcd2aaa03d54630a23d3d/symphony-bdk-http/symphony-bdk-http-webclient/src/main/java/com/symphony/bdk/http/webclient/ApiClientWebClient.java#L233-L247 and https://github.com/finos/symphony-bdk-java/blob/b77d36a2ca6fa6000f8fcd2aaa03d54630a23d3d/symphony-bdk-http/symphony-bdk-http-jersey2/src/main/java/com/symphony/bdk/http/jersey2/ApiClientJersey2.java#L426-L466
It has the advantage of not breaking the API
- or we update the `HttpClient.RequestConfig` class so that it contains a `MultiValuedMap` as formParams and we pass a Map<String, List<Object>> as formParams in the `invokeApi` method: https://github.com/finos/symphony-bdk-java/blob/b77d36a2ca6fa6000f8fcd2aaa03d54630a23d3d/symphony-bdk-http/symphony-bdk-http-api/src/main/java/com/symphony/bdk/http/api/HttpClient.java#L378
We will still need to do the above (handing a `List<File>` as formParam value)
However this will break the current contract/API (note that `MultiValuedMap<K,V>` extends `Map<K, List<V>>`)
